<a href="https://colab.research.google.com/github/Mintu-Vipin/NPowerCanada_JuniorDataAnalyst/blob/main/Course7Week3_Exploratory_data_analysis_with_Pandas(dataset_adult).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import packages
import pandas as pd
import numpy as np

In [2]:
# Load data
df = pd.read_csv('adult.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              32561 non-null  int64
 1   workclass        32561 non-null  object
 2   fnlwgt           32561 non-null  int64
 3   education        32561 non-null  object
 4   educational-num  32561 non-null  int64
 5   marital-status   32561 non-null  object
 6   occupation       32561 non-null  object
 7   relationship     32561 non-null  object
 8   race             32561 non-null  object
 9   gender           32561 non-null  object
 10  capital-gain     32561 non-null  int64
 11  capital-loss     32561 non-null  int64
 12  hours-per-week   32561 non-null  int64
 13  native-country   32561 non-null  object
 14  income           32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)
# Remove rows containing NaN values
df.dropna()
df.reset_index(drop=True, inplace=True)
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [5]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [6]:
df.describe(include = 'object')

,workclass,education,marital-status,occupation,relationship,race,gender,native-country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

In [7]:
# 1. How many men and women (sex feature) are represented in this dataset?
df['gender'].value_counts()

 Male      21790
 Female    10771
Name: gender, dtype: int64

In [8]:
# 2. What is the average age (age feature) of women?
# Filter the DataFrame to include only women
women_df = df[df['gender'] == ' Female']

# Calculate the average age of women
average_age_women = women_df['age'].mean()
print(f'Average age of women is {average_age_women}')

Average age of women is 36.85823043357163

In [9]:
# 3. What is the percentage of German citizens (native-country feature)?
german_count = df[df['native-country'] ==' Germany'].shape[0]
count_total = df.shape[0]
print(f'Percentage of German citizens is {(german_count/count_total) *100}')

Percentage of German citizens is 0.42074874850281013

In [10]:
# 4. What are the mean and standard deviation of age for those who earn more than 50K per year (salary feature) and those who earn less than 50K per year?

# Filter DataFrame for individuals earning more than 50K per year
high_income_df = df[df['income'] == ' >50K']

# Filter DataFrame for individuals earning less than or equal to 50K per year
low_income_df = df[df['income'] == ' <=50K']

# Calculate mean and standard deviation of age for both groups
mean_age_high_income = high_income_df['age'].mean()
std_dev_age_high_income = high_income_df['age'].std()

mean_age_low_income = low_income_df['age'].mean()
std_dev_age_low_income = low_income_df['age'].std()

print("For individuals earning more than 50K per year:")
print("Mean age:", mean_age_high_income)
print("Standard deviation of age:", std_dev_age_high_income)

print("\nFor individuals earning less than or equal to 50K per year:")
print("Mean age:", mean_age_low_income)
print("Standard deviation of age:", std_dev_age_low_income)

For individuals earning more than 50K per year:
Mean age: 44.24984058155847
Standard deviation of age: 10.519027719851826

For individuals earning less than or equal to 50K per year:
Mean age: 36.78373786407767
Standard deviation of age: 14.02008849082488

In [11]:
# 5. Is it true that people who earn more than 50K have at least a high school
# education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

# Filter DataFrame for individuals earning more than 50K per year
high_income_df = df[df['income'] == ' >50K']

# Define a list of education levels considered as at least high school
high_school_education = [' Bachelors', ' Prof-school', ' Assoc-acdm', ' Assoc-voc', ' Masters', ' Doctorate']

# Filter the high income DataFrame for individuals with education levels lower than high school
low_education_high_income_df = high_income_df[~high_income_df['education'].isin(high_school_education)]

# Check if there are any individuals in the filtered DataFrame
# If the DataFrame is empty, it means all individuals earning more than 50K have at least a high school education
if low_education_high_income_df.empty:
    print("True, all people earning more than 50K have at least a high school education.")
else:
    print("False, there are individuals earning more than 50K without at least a high school education.")

False, there are individuals earning more than 50K without at least a high school education.

In [12]:
# 6. Display age statistics for each race (race feature) and each gender (sex feature). Use groupby() and describe().
# Find the maximum age of men of Amer-Indian-Eskimo race.

# Display age statistics for each race and gender
age_stats = df.groupby(['race', 'gender'])['age'].describe()
print("Age statistics for each race and gender:")
age_stats

Age statistics for each race and gender:

                               count       mean        std   min   25%   50%  \
race                gender
 Amer-Indian-Eskimo  Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                     Male      192.0  37.208333  12.049563  17.0  28.0  35.0
 Asian-Pac-Islander  Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                     Male      693.0  39.073593  12.883944  18.0  29.0  37.0
 Black               Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                     Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
 Other               Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                     Male      162.0  34.654321  11.355531  17.0  26.0  32.0
 White               Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                     Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                               75%   max
race                gender
 Amer-Indian-Eskimo  Female  46.00  80.0
                     Male    45.00  82.0
 Asian-Pac-Islander  Female  43.75  75.0
                     Male    46.00  90.0
 Black               Female  46.00  90.0
                     Male    46.00  90.0
 Other               Female  39.00  74.0
                     Male    42.00  77.0
 White               Female  46.00  90.0
                     Male    49.00  90.0

In [13]:
# Find the maximum age of men of Amer-Indian-Eskimo race
filtered_data = df[(df['race'] == ' Amer-Indian-Eskimo') & (df['gender'] == ' Male')]
max_age_amer_indian_eskimo_men = filtered_data['age'].max()
print("Maximum age of men of Amer-Indian-Eskimo race:", max_age_amer_indian_eskimo_men)

Maximum age of men of Amer-Indian-Eskimo race: 82

In [14]:
# 7. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (marital-status feature)?
# Consider as married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent
# or Married-AF-spouse), the rest are considered bachelors.

# Filter the DataFrame for men
men_df = df[df['gender'] == ' Male']

# Categorize marital status into 'Married' and 'Single'
men_df.loc[:, 'marital_status_category'] = men_df['marital-status'].apply(lambda x: ' Married' if x.startswith(' Married') else ' Single')

# Calculate the total count of married and single men
total_married_men = men_df[men_df['marital_status_category'] == ' Married'].shape[0]
total_single_men = men_df[men_df['marital_status_category'] == ' Single'].shape[0]

# Calculate the count of married and single men earning >50K
married_men_high_earners = men_df[(men_df['marital_status_category'] == ' Married') & (men_df['income'] == '>50K')].shape[0]
single_men_high_earners = men_df[(men_df['marital_status_category'] == ' Single') & (men_df['income'] == '>50K')].shape[0]

# Calculate the proportion of high earners among married and single men
proportion_high_earners_married = married_men_high_earners / total_married_men
proportion_high_earners_single = single_men_high_earners / total_single_men

# Determine which group has a greater proportion of high earners
if proportion_high_earners_married > proportion_high_earners_single:
    print("The proportion of married men earning >50K is greater.")
elif proportion_high_earners_married < proportion_high_earners_single:
    print("The proportion of single men earning >50K is greater.")
else:
    print("The proportions of married and single men earning >50K are equal.")

men_df

The proportions of married and single men earning >50K are equal.

<ipython-input-14-c25f37b2d1c3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  men_df.loc[:, 'marital_status_category'] = men_df['marital-status'].apply(lambda x: ' Married' if x.startswith(' Married') else ' Single')

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,marital_status_category
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,Single
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,Married
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,Single
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,Married
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K,Married
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K,Single
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K,Married
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K,Single
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,Married
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,Single

In [15]:
# 8. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours, and
# what is the percentage of those who earn a lot (>50K) among them?

# the maximum number of hours a person works per week
max_hours_per_week =df['hours-per-week'].max()

# Count the number of people who work the maximum number of hours
num_people_max_hours =  df[df['hours-per-week'] == max_hours_per_week].shape[0]

# Calculate the percentage of individuals earning >50K among those who work the maximum number of hours

percentage_of_individuals = df[(df['hours-per-week'] == max_hours_per_week) & (df['income'] == '>50K')].shape[0]

print(f'{ max_hours_per_week }\n{num_people_max_hours}\n{percentage_of_individuals}')

99
85
0

In [16]:
# 9. Count the average time of work (hours-per-week) for those who earn a little and a lot (salary) for each country (native-country). What will these be for Japan?

avg_time = df.groupby(['income', 'native-country'])['hours-per-week'].mean()
print(avg_time,'\n\n\n')

avg_time_japan = avg_time.loc[(slice(None), ' Japan')]
avg_time_japan

income  native-country
 <=50K   ?                  40.164760
         Cambodia           41.416667
         Canada             37.914634
         China              37.381818
         Columbia           38.684211
                              ...
 >50K    Thailand           58.333333
         Trinadad&Tobago    40.000000
         United-States      45.505369
         Vietnam            39.200000
         Yugoslavia         49.500000
Name: hours-per-week, Length: 82, dtype: float64

income
 <=50K    41.000000
 >50K     47.958333
Name: hours-per-week, dtype: float64

In [17]:
# 10. Find out the total number of hours worked as per different occupations.
# df.groupby(['occupation', 'hours-per-week'])['income']

occupation_hours= df.groupby('occupation')['hours-per-week'].sum()
occupation_hours

occupation
 ?                     58803
 Adm-clerical         141595
 Armed-Forces            366
 Craft-repair         173405
 Exec-managerial      182920
 Farming-fishing       46708
 Handlers-cleaners     51988
 Machine-op-inspct     81593
 Other-service        114342
 Priv-house-serv        4900
 Prof-specialty       175481
 Protective-serv       27823
 Sales                148851
 Tech-support          36593
 Transport-moving      71316
Name: hours-per-week, dtype: int64